<?php

namespace TodoListBundle\Repository;

/**
 * TodoListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
interface ITodoListRepository extends ICommonRepository
{	
	/**
	 * Search for lists by their names.
	 */
	public function searchByName($name, $offset = 0, $limit = null);
	
	/**
	 * Gives all lists of the given type.
	 */
	public function findByType($type, $offset = 0, $limit = null);
}
