<?php

namespace TodoListBundle\Repository;

/**
 * TodoListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
interface TodoListRepository
{
	/**
	 * Gives all the lists.
	 */
	public function findAll($offset = 0, $limit = null);
	
	/**
	 * Search for lists by their names.
	 */
	public function searchByName($name, $offset = 0, $limit = null);
	
	/**
	 * Gives all lists of the given type.
	 */
	public function findByType($type, $offset = 0, $limit = null);
	
	/**
	 * Gives the list corresponding to the given identifier if it exists
	 * and null otherwise.
	 */
	public function getById($id);
}
